#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%

; It captures all the keys and types ‘haha’
*a::SendInput haha
*b::SendInput haha
*c::SendInput haha
*d::SendInput haha
*e::SendInput haha
*f::SendInput haha
*g::SendInput haha
*h::SendInput haha
*i::SendInput haha
*j::SendInput haha
*k::SendInput haha
*l::SendInput haha
*m::SendInput haha
*n::SendInput haha
*o::SendInput haha
*p::SendInput haha
*q::SendInput haha
*r::SendInput haha
*s::SendInput haha
*t::SendInput haha
*u::SendInput haha
*v::SendInput haha
*w::SendInput haha
*x::SendInput haha
*y::SendInput haha
*z::SendInput haha
*1::SendInput haha
*2::SendInput haha
*3::SendInput haha
*4::SendInput haha
*5::SendInput haha
*6::SendInput haha
*7::SendInput haha
*8::SendInput haha
*9::SendInput haha
*0::SendInput haha
*Space::SendInput haha
*Enter::SendInput haha
*Tab::SendInput haha
*Backspace::SendInput haha
*CapsLock::SendInput haha
*Shift::SendInput haha
*Ctrl::SendInput haha
*Alt::SendInput haha
*F1::SendInput haha
*F2::SendInput haha
*F3::SendInput haha
*F4::SendInput haha
*F5::SendInput haha
*F6::SendInput haha
*F7::SendInput haha
*F8::SendInput haha
*F9::SendInput haha
*F10::SendInput haha
*F11::SendInput haha
*F12::SendInput haha
